feat: 安卓端保活策略介绍
sealdice/sealdice-manual-next pull request #135
Opened 2024-04-10 11:42 UTC by oissevalt

Feel free to add more content.

2024-04-10 12:01 UTC, JustAnotherID requested changes

2024-04-10 12:01 UTC, JustAnotherID commented on docs/deploy/android_keepalive.md
> +<img src="./images/keepalive_coloros_launch.jpg" width="450">
```suggestion
<img src="./images/keepalive_coloros_launch.jpg" width="50%">
```

2024-04-10 12:01 UTC, JustAnotherID commented on docs/deploy/android_keepalive.md
> +<img src="./images/keepalive_coloros_nightshift.jpg" width="500">
```suggestion
<img src="./images/keepalive_coloros_nightshift.jpg" width="50%">
```

2024-04-10 12:01 UTC, JustAnotherID commented on docs/deploy/android_keepalive.md
> +<img src="./images/keepalive_miui_multitask.jpg" width="450">
```suggestion
<img src="./images/keepalive_miui_multitask.jpg" width="50%">
```

2024-04-10 12:01 UTC, JustAnotherID commented on docs/deploy/android_keepalive.md
> +<img src="./images/keepalive_harmonyos_multitask.jpg" width="450">
```suggestion
<img src="./images/keepalive_harmonyos_multitask.jpg" width="50%">
```

2024-04-10 12:01 UTC, JustAnotherID commented on docs/deploy/android_keepalive.md
> +<img src="./images/keepalive_coloros_multitask.jpg" width="450">
```suggestion
<img src="./images/keepalive_coloros_multitask.jpg" width="50%">
```

2024-04-10 12:01 UTC, JustAnotherID commented on docs/deploy/android_keepalive.md
> +<img src="./images/keepalive_inapp.jpg" width="450">
```suggestion
<img src="./images/keepalive_inapp.jpg" width="50%">
```

2024-04-10 12:06 UTC, oissevalt commented
@JustAnotherID 图片 width="50%" 的话，手机端的显示效果不是很好

2024-04-10 12:23 UTC, JustAnotherID commented
> @JustAnotherID 图片 width="50%" 的话，手机端的显示效果不是很好

不是 50% 的话 PC 端展示很差……

2024-04-11 02:17 UTC, Xiangze-Li commented
有可能的话找个仓库把分支部署到pages看看效果？

2024-04-11 06:13 UTC, Xiangze-Li approved these changes
LGTM

2024-04-11 06:21 UTC, Xiangze-Li approved these changes
LGTM

2024-04-11 06:21 UTC, JustAnotherID approved these changes
LGTM

2024-04-11 06:21 UTC, merged