修改安卓端保活策略介绍
sealdice/sealdice-manual-next pull request #139
Opened 2024-04-11 13:12 UTC by MX-fox

2024-04-12 02:21 UTC, Xiangze-Li requested changes

2024-04-12 02:21 UTC, Xiangze-Li commented on docs/deploy/android_keepalive.md
> +初次启动时提示是否运行“海豹核心”发送通知，选择「始终允许」
typo 和句尾标点

```suggestion
初次启动时提示是否允许“海豹核心”发送通知，选择「始终允许」。
```

2024-04-12 02:21 UTC, Xiangze-Li commented on docs/deploy/android_keepalive.md
> -## 系统设置
标题等级在增加时应该递增，删除此项目导致从 1 级标题跳跃到 3 级标题

2024-04-12 02:21 UTC, Xiangze-Li commented on docs/deploy/android_keepalive.md
> +第二步，在海豹核心的后台配置中选择「无限制」
句尾标点

2024-04-12 02:21 UTC, Xiangze-Li commented on docs/.vitepress/catalogue.ts
> +        { text: "配置安卓端保活", link: "/deploy/android_keepalive"},
保持空格

2024-04-12 02:21 UTC, Xiangze-Li commented on docs/.vitepress/catalogue.ts
> +         link: "/deploy/android_keepalive" ,
缩进和对齐

2024-04-12 16:57 UTC, fy0 approved these changes

2024-04-13 08:41 UTC, Xiangze-Li approved these changes
LGTM

2024-04-13 17:22 UTC, merged