docs(fun):指令迁移
sealdice/sealdice-manual-next pull request #177
Opened 2024-05-10 13:38 UTC by MX-fox

close #175

2024-05-10 14:14 UTC, JustAnotherID requested changes
把 fun.md 里的「娱乐」字样也一并改成「功能」吧，现在 fun 的含义是 function 了（
别忘记导航栏和目录里的名字。

可以参考目前 core 里的描述改一改：
```text
功能扩展，主要提供快捷指令、ping、welcome等额外指令，同时也包括今日人品、智能鸽子等娱乐相关指令。此外，小众规则指令暂时也放在本扩展中
```

2024-05-11 12:21 UTC, JustAnotherID requested changes

2024-05-11 12:21 UTC, JustAnotherID commented on docs/use/fun.md
> +{content: '🕊️: 前往了一个以前捕鲸的小岛度假~这里人很亲切！但是吃了这里的鱼肉料  理之后有点晕晕的诶...想到前几天<木落>的短信，还是别追究他为什么不在了。\n\t——鹊鹊结合实际经历创作'},
为啥多了个空格？

2024-05-11 12:55 UTC, Xiangze-Li approved these changes

2024-05-11 12:56 UTC, merged