docs(deploy): 增加通过 docker compose 同时部署海豹与 Lagrange 相关说明
sealdice/sealdice-manual-next pull request #188
Opened 2024-05-19 16:33 UTC by MintCider

2024-05-19 17:15 UTC, JustAnotherID requested changes
Docker 相关单独放一个页面，不要混在 QQ 部署中。

2024-05-19 17:43 UTC, MintCider commented
> Docker 相关单独放一个页面，不要混在 QQ 部署中。

行 白天搞

2024-05-20 10:26 UTC, Xiangze-Li commented on docs/deploy/platform-qq-docker.md
> +    user: <uid>:<gid>
不要使用这一行配置。在镜像里以非 root 用户执行会导致一些权限问题。

2024-05-20 10:30 UTC, MintCider commented on docs/deploy/platform-qq-docker.md
> +    user: <uid>:<gid>
好吧 不给Root一般是出于安全考虑来着 另外会导致宿主机绑定的文件需要root权限才能读写……

我改下吧

2024-05-21 01:09 UTC, Xiangze-Li commented on docs/deploy/platform-qq-docker.md
> +      - ./lagrange_data:/app/data
最新经验：还需要把海豹镜像的 /data 目录也挂载到拉格兰的 /data 路径，这样在发送图片时两边才能通过相同路径访问到正确的图片。大概是在拉格兰的目录挂载中添加一条 `./seal_data:/data`

2024-05-21 04:49 UTC, MintCider commented on docs/deploy/platform-qq-docker.md
> +      - ./lagrange_data:/app/data
喔 原来发送图片是通过绝对地址实现的么
那看来不通过 docker compose 部署的其他后端都没办法正常处理啊

2024-05-21 04:50 UTC, Xiangze-Li commented on docs/deploy/platform-qq-docker.md
> +      - ./lagrange_data:/app/data
问题不大，docker用户会自己适应的

2024-05-21 04:59 UTC, MintCider commented on docs/deploy/platform-qq-docker.md
> +      - ./lagrange_data:/app/data
是否需要提醒用户后续配置牌堆或自定义回复时，必须将图片放在 `seal_data` 下？

[SealDice 文件目录树](https://docs.sealdice.com/deploy/about_file.html#sealdice-%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95%E6%A0%91)这一节写明了
> 海豹为了安全不允许调用非海豹文件夹内的图片

或许不用提醒了？

2024-05-21 05:00 UTC, MintCider commented on docs/deploy/platform-qq-docker.md
> +      - ./lagrange_data:/app/data
> 问题不大，docker用户会自己适应的

好好好 我就是自适应用户（x

- - -

不知道以后会不会有支持 Data URI 的后端

2024-05-21 05:03 UTC, Xiangze-Li commented on docs/deploy/platform-qq-docker.md
> +      - ./lagrange_data:/app/data
> 是否需要提醒用户后续配置牌堆或自定义回复时，必须将图片放在 `seal_data` 下？

对于海豹来说文件内容放在 ./data 目录是默认的，不必单独写了

2024-05-21 05:20 UTC, MintCider commented on docs/deploy/platform-qq-docker.md
> +      - ./lagrange_data:/app/data
8好意思 好像 Resolve Conversation 不该我来点（x

2024-05-21 05:26 UTC, Xiangze-Li commented on docs/deploy/platform-qq-docker.md
> +      - ./lagrange_data:/app/data
没问题，实际修改了内容的人来resolve是正确的

2024-05-21 05:27 UTC, Xiangze-Li commented
@JustAnotherID 再来看看

2024-05-21 05:48 UTC, JustAnotherID approved these changes

2024-05-21 05:48 UTC, merged