docs(QQ):增加pc端协议关闭戳一戳的提醒
sealdice/sealdice-manual-next pull request #220
Opened 2024-07-10 15:19 UTC by kenichiLyon

rt

2024-07-10 15:20 UTC, kenichiLyon commented
前面的优化表述不知道怎么回事计入了commit，很早的了，这个可以忽略

2024-07-11 01:11 UTC, Xiangze-Li requested changes

2024-07-11 01:11 UTC, Xiangze-Li commented on docs/deploy/images/platform-qq-turnoff.png
1. 此截图只是标出了单个选项的位置，意义不大
2. 即使要标，也应使用图形，而不是鼠标画圈

2024-07-11 01:11 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +同时，由于PC端协议并未**完全实现戳一戳的功能。**建议使用上述客户端连接QQ的用户关闭海豹核心后台位于`基本设置`的`启用戳一戳`开关，以免带来不必要的报错和麻烦。
```suggestion
同时，由于 PC 端协议**并未完全实现**戳一戳功能。请使用上述客户端连接 QQ 的用户关闭海豹核心后台位于 `基本设置` 的 `启用戳一戳` 开关，以免产生不必要的报错和麻烦。
```

2024-07-11 01:11 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +同时，由于PC端协议并未**完全实现戳一戳的功能。**建议使用上述客户端连接QQ的用户关闭海豹核心后台位于`基本设置`的`启用戳一戳`开关，以免带来不必要的报错和麻烦。
此段内容放在了 内置客户端 一节的前面。由于内置客户端也是 PC 协议，这是不合适的

2024-07-11 03:52 UTC, Xiangze-Li requested changes

2024-07-11 03:52 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +
1. LLOB 和 NCQQ 实现了戳一戳吗？如果没有实现，这就是不完全的
2. 内置客户端也是拉格兰，但用户不知道

2024-07-11 11:40 UTC, kenichiLyon commented on docs/deploy/platform-qq.md
> +
采用pc端NTQQ协议登录的协议端都尚未做到群聊戳一戳（官方对于群聊戳一戳的实现实质上和私聊不同）
此处我还是把它回滚到第一次提交的版本，同时提前到`对接引导` 处吗？

2024-07-11 13:57 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +
我想放最前面应该是可以的，可以试一下效果

> （官方对于群聊戳一戳的实现实质上和私聊不同）

这个说明要不要两可

2024-07-12 03:47 UTC, MX-fox commented
https://github.com/sealdice/sealdice-manual-next/blob/905f0fd6354820933fbc0512d406d32767b28db2/docs/config/basic.md?plain=1#L64
建议同样补上说明

2024-07-12 05:58 UTC, Xiangze-Li approved these changes

2024-07-12 05:59 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +
按暮星所提到的，这里应相似地做出说明

https://github.com/sealdice/sealdice-manual-next/blob/905f0fd6354820933fbc0512d406d32767b28db2/docs/config/basic.md?plain=1#L64

2024-07-14 07:09 UTC, MX-fox commented on docs/config/basic.md
> +:::
```suggestion
由于最新版 NTQQ 暂不支持戳一戳，所以 内置客户端/Lagrange/NapCat/LLOneBot 等基于 NTQQ 的连接方案均无法回应戳一戳，同时建议使用上述客户端连接 QQ 的用户**关闭此开关**，以免产生不必要的报错和麻烦。
```
这里就是开关介绍，不用写那么复杂。

2024-07-14 07:21 UTC, MX-fox commented on docs/config/basic.md
> +:::
多了:::

2024-07-14 20:19 UTC, MX-fox approved these changes
LGTM

2024-07-14 20:37 UTC, merged