为 js_api_list.md 中增添了解释
sealdice/sealdice-manual-next pull request #250
Opened 2024-08-10 05:50 UTC by bugtower100

添加了一下.chopPrefixToArgsWith(ss...)这个api的解释（用词可能有些不专业，尽可能用简洁易懂的方式写了）

2024-08-17 23:08 UTC, bugtower100 commented
> 添加了一下.chopPrefixToArgsWith(ss...)这个api的解释（用词可能有些不专业，尽可能用简洁易懂的方式写了）

2024-09-02 17:01 UTC, kenichiLyon commented on docs/advanced/js_api_list.md
> +.chopPrefixToArgsWith(ss...) // 似乎是为读取匹配到的参数 ss 前后添加空格
这部分用词不推荐用「似乎」。另外可以看看实际的效果吗？

2024-10-04 14:55 UTC, bugtower100 commented on docs/advanced/js_api_list.md
> +.chopPrefixToArgsWith(ss...) // 似乎是为读取匹配到的参数 ss 前后添加空格
用似乎确实不太准确，经过后面实践我认为应该表示为“为切掉了匹配到的参数 ss 前后所需的空格”，实际的使用效果如下：
我设置了一个名为"mg"的指令名：cmdmg.name='mg';//指令名
然后在最开始使用了.chopPrefixToArgsWith(ss...)这个api（如下）
cmdmg.solve=(ctx,msg,cmdArgs)=>{
    cmdArgs.chopPrefixToArgsWith("h")
 （后面省略）
}
这样当我在使用指令时就可以直接用.mgh来获得我想要的效果了，如果没有用这个的话，使用指令时mg和h之间就要用空格隔开（否则会出现错误）

> 这部分用词不推荐用「似乎」。另外可以看看实际的效果吗？

2024-10-04 14:57 UTC, bugtower100 commented on docs/advanced/js_api_list.md
> +.chopPrefixToArgsWith(ss...) // 似乎是为读取匹配到的参数 ss 前后添加空格
> 用似乎确实不太准确，经过后面实践我认为应该表示为“为切掉了匹配到的参数 ss 前后所需的空格”，实际的使用效果如下： 我设置了一个名为"mg"的指令名：cmdmg.name='mg';//指令名 然后在最开始使用了.chopPrefixToArgsWith(ss...)这个api（如下） cmdmg.solve=(ctx,msg,cmdArgs)=>{ cmdArgs.chopPrefixToArgsWith("h") （后面省略） } 这样当我在使用指令时就可以直接用.mgh来获得我想要的效果了，如果没有用这个的话，使用指令时mg和h之间就要用空格隔开（否则会出现错误）
> 
> > 这部分用词不推荐用「似乎」。另外可以看看实际的效果吗？

另外这个api有个限制，就是它只能切去第一个关键词地空格，假设现在需要mghw（h、w分别为第一第二个变量），不论在哪里添加.chopPrefixToArgsWith(w)都是没有办法实现的。

2024-10-11 09:58 UTC, kenichiLyon requested changes

2024-10-11 09:58 UTC, kenichiLyon commented on docs/advanced/js_api_list.md
> +.chopPrefixToArgsWith(ss...) // 似乎是为读取匹配到的参数 ss 前后添加空格
```suggestion
.chopPrefixToArgsWith(ss...) // 切掉匹配到的参数 ss 前后所需的空格
```

2024-10-11 15:26 UTC, kenichiLyon submitted a review, later dismissed

2024-12-06 15:38 UTC, fy0 commented
```
.chopPrefixToArgsWith(ss...) // 切掉匹配到的参数 ss 前后所需的空格
```

这个函数的真实作用：
将未写空格的指令参数切开，就如同写了空格那样。使用传入的数组ss进行前缀匹配来决定切什么。
这是一个用例，log命令

```go
cmdArgs.ChopPrefixToArgsWith("on", "off", "del", "rm", "masterget", "get", "end", "halt", "list", "new", "stat", "export")

```

他会将 `.log on测试` 切成 `.log on 测试` 的标准格式。切开后我们会得到 ['on', '测试'] 这样的指令信息，替代原来的 ['on测试']
其他指令参数同理。

2025-03-07 17:23 UTC, kenichiLyon requested changes

2025-03-07 17:23 UTC, kenichiLyon commented on docs/advanced/js_api_list.md
> +.chopPrefixToArgsWith(ss...) // 切掉匹配到的参数 ss 前后所需的空格
```suggestion
.chopPrefixToArgsWith(ss...) //将未写空格的指令参数切开，就如同写了空格那样。使用传入的数组ss进行前缀匹配来决定怎么切。
```

2026-09-10 00:18 UTC, kenichiLyon commented
在 #337 内修复

2026-09-10 00:18 UTC, closed without merging