add:新增「紧急补天指南」界面
sealdice/sealdice-manual-next pull request #90
Opened 2024-02-15 05:04 UTC by kenichiLyon

-新增了「紧急补天指南」界面，通过编写界面给目前用户群中未曾使用过开源程序的用户进行科普
-目前已对「个人计算机和服务器的区别」以及「内存不足的区分」问题进行教程编写。但是对于其他问题暂时没有想法，希望各位可以通过review给予建议。

2024-02-15 05:08 UTC, Xiangze-Li requested changes
1. 导航栏
2. 索引页
3. 换行
4. 标点符号规范使用

2024-02-15 05:43 UTC, Szzrain commented
建议参考 #58 进行补全

2024-02-15 08:48 UTC, JustAnotherID commented
1. 「紧急补天指南」这个标题似乎不太合适，没有直观地表达出具体内容，建议改为如「相关科普」之类的名字。
2.  后半部分属于答疑的内容建议转移到「使用-常见问题」页。

2024-02-23 09:55 UTC, Xiangze-Li requested changes

2024-02-23 09:55 UTC, Xiangze-Li commented on docs/.vuepress/navbar.ts
> +    prefix: "/for_ 0/",
1. 这里的空格是想要的吗？
2. 下面的缩进需要整理干净

2024-02-23 10:47 UTC, Xiangze-Li approved these changes
lgtm

2024-02-23 10:57 UTC, merged