new：llobapi添加
sealdice/sealdice-manual-next pull request #91
Opened 2024-02-17 15:20 UTC by yichirehuijian

新增llntobapi
新增237处理方式

2024-02-17 17:19 UTC, FlameTEXT commented on docs/deploy/platform-qq.md
> +
- 不支持 CQ 码

最好把此方案的局限性一并列举

2024-02-17 17:19 UTC, FlameTEXT commented on docs/deploy/platform-qq.md
> +2. 让他人帮助你滑条。
推荐修改为：

2. 内置的 ticket 抓取工具失效，需要手动抓取（这里添加一个手动抓取的教程，最好让阅读手册自己先尝试再请求别人帮助）

2024-02-17 22:21 UTC, Xiangze-Li requested changes
同时建议补充空行。MarkDown 习惯上在不同元素（如标题和正文、正文和内容块等）之间使用正好 1 个空行。这有助于避免解析错误，也使阅读源代码更简单。

2024-02-17 22:21 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +*Liteloader* 是 NTQQ 的插件加载器，允许通过插件注入 QQ 实现某些特定的功能，例如 *Liteloader-OnebotApi*（以下简称 LLObApi），可以实现劫持客户端对外开放 API ，可以理解为装在 PC 上的 Shamrock。
在正文的开头也需提及引入此功能的版本

2024-02-17 22:21 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +:::info 介绍 liteloader-onebotapi
注意大小写：LiteLoader-OneBotAPI，或符合此插件原始名字的大小写组合

2024-02-17 22:21 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +*Liteloader* 是 NTQQ 的插件加载器，允许通过插件注入 QQ 实现某些特定的功能，例如 *Liteloader-OnebotApi*（以下简称 LLObApi），可以实现劫持客户端对外开放 API ，可以理解为装在 PC 上的 Shamrock。
注意大小写：LiteLoader

2024-02-17 22:21 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +*Liteloader* 是 NTQQ 的插件加载器，允许通过插件注入 QQ 实现某些特定的功能，例如 *Liteloader-OnebotApi*（以下简称 LLObApi），可以实现劫持客户端对外开放 API ，可以理解为装在 PC 上的 Shamrock。
不建议引入新的缩写。称为 OneBotAPI 即可

2024-02-17 22:21 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +安装完成后重新登录 QQ，默认开放的正向ws端口为 3001，在海豹的新添账号选择 ONEBOT 分离部署，账号处随便填写，连接地址填 **ws://localhost:3001** 就看到登录成功了！
注意大小写：OneBot

2024-02-17 22:21 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +:::warning 一些坑
建议用语调整：已知问题

2024-02-17 22:21 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +- 非 win 用户使用一键脚本时要安装 git ，具体方法见 [git官网](https://git-scm.com/)。
不够普遍的缩写：建议直接使用 Windows

2024-02-18 01:13 UTC, yichirehuijian commented on docs/deploy/platform-qq.md
> +
![image](https://github.com/sealdice/sealdice-manual-next/assets/123849685/c50f0d17-572b-4004-a766-4af434d541e6)
CQ码是支持的，这里使用的OneBotAPI适配可以看到CQ码，也测试过网络请求也可使用，但是调用本地暂时还没测试

2024-02-18 15:44 UTC, Xiangze-Li requested changes

2024-02-18 15:44 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +- 运行 Lagrange 需要 [.NET](https://dotnet.microsoft.com/download)，安装对应拉格郎日的版本（例如拉格朗日后面是 7 则需安装 SDK 的版本为 7）。
拉格朗日：拉格兰

2024-02-18 15:44 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +- 非 windows 使用一键脚本，请在系统中配置 [git官网](https://git-scm.com/)。
此句会渲染为「请在系统中配置git官网」，不通

2024-02-18 15:44 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +所指处即插件文件夹，打开这个文件夹并且在Plugins新建一个文件夹，把OneBotAPI **Release** 版本的四个文件解压到新建的文件夹处，重启 QQ 即可。
中文西文之间空格，参照本仓库 readme 中排版指北

2024-02-18 16:03 UTC, kagangtuya-star commented on docs/deploy/platform-qq.md
> +
可以支持本地的图片调用，下午用cq码图文混排的牌堆测试过

2024-02-18 23:54 UTC, Xiangze-Li commented on docs/deploy/platform-qq.md
> +*Liteloader* 是 NTQQ 的插件加载器，允许通过插件注入 QQ 实现某些特定的功能，例如 *Liteloader-OnebotApi*（以下简称 LLObApi），可以实现劫持客户端对外开放 API ，可以理解为装在 PC 上的 Shamrock。
「从某版本起，海报支持……」

可以参考指令介绍部分

2024-02-19 03:24 UTC, Xiangze-Li commented
去掉了 手动抓取 ticket 的文本说明：与已有内容重复

2024-02-19 03:25 UTC, Xiangze-Li commented
预览：<https://xiangze-li.github.io/sealdice-manual-next/deploy/platform-qq.html>

2024-02-19 07:54 UTC, JustAnotherID approved these changes
LGTM

2024-02-19 07:55 UTC, merged